//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CommonArea
{
    public partial class FormCommon
    {
        public int FormID { get; set; }
        public int EmployeeID { get; set; }
        public DateTime Date { get; set; }
        public int TotalAmount { get; set; }
        public string Status { get; set; }

        public FormCommon()
        {

        }
        public FormCommon(int FormID, int EmployeeID, System.DateTime Date, int TotalAmount, string Status)
        {
            this.FormID = FormID;
            this.EmployeeID = EmployeeID;
            this.Date = Date;
            this.TotalAmount = TotalAmount;
            this.Status = Status;
        }
    }
}
